// Code generated by "stringer -type=Role"; DO NOT EDIT.

package raft

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RoleFollower-0]
	_ = x[RoleCandidate-1]
	_ = x[RoleLeader-2]
}

const _Role_name = "RoleFollowerRoleCandidateRoleLeader"

var _Role_index = [...]uint8{0, 12, 25, 35}

func (i Role) String() string {
	if i >= Role(len(_Role_index)-1) {
		return "Role(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Role_name[_Role_index[i]:_Role_index[i+1]]
}
