// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: consensus/raft/raftproto/raftproto.proto

package raftproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntryType int32

const (
	EntryType_EntrySystem EntryType = 0
	EntryType_EntryUser   EntryType = 1
)

// Enum value maps for EntryType.
var (
	EntryType_name = map[int32]string{
		0: "EntrySystem",
		1: "EntryUser",
	}
	EntryType_value = map[string]int32{
		"EntrySystem": 0,
		"EntryUser":   1,
	}
)

func (x EntryType) Enum() *EntryType {
	p := new(EntryType)
	*p = x
	return p
}

func (x EntryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntryType) Descriptor() protoreflect.EnumDescriptor {
	return file_consensus_raft_raftproto_raftproto_proto_enumTypes[0].Descriptor()
}

func (EntryType) Type() protoreflect.EnumType {
	return &file_consensus_raft_raftproto_raftproto_proto_enumTypes[0]
}

func (x EntryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntryType.Descriptor instead.
func (EntryType) EnumDescriptor() ([]byte, []int) {
	return file_consensus_raft_raftproto_raftproto_proto_rawDescGZIP(), []int{0}
}

type Entry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Term  uint64    `protobuf:"varint,10,opt,name=Term,proto3" json:"Term,omitempty"`
	Index uint64    `protobuf:"varint,20,opt,name=Index,proto3" json:"Index,omitempty"`
	Type  EntryType `protobuf:"varint,30,opt,name=Type,proto3,enum=proto.EntryType" json:"Type,omitempty"`
	Data  []byte    `protobuf:"bytes,40,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *Entry) Reset() {
	*x = Entry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consensus_raft_raftproto_raftproto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_raft_raftproto_raftproto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_consensus_raft_raftproto_raftproto_proto_rawDescGZIP(), []int{0}
}

func (x *Entry) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *Entry) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Entry) GetType() EntryType {
	if x != nil {
		return x.Type
	}
	return EntryType_EntrySystem
}

func (x *Entry) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_consensus_raft_raftproto_raftproto_proto protoreflect.FileDescriptor

var file_consensus_raft_raftproto_raftproto_proto_rawDesc = []byte{
	0x0a, 0x28, 0x63, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x2f, 0x72, 0x61, 0x66, 0x74,
	0x2f, 0x72, 0x61, 0x66, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x61, 0x66, 0x74, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x6b, 0x0a, 0x05, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x65,
	0x72, 0x6d, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x54, 0x65, 0x72, 0x6d, 0x12, 0x14,
	0x0a, 0x05, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x14, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x12, 0x24, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x1e, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x28, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x2a, 0x2b,
	0x0a, 0x09, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x55, 0x73, 0x65, 0x72, 0x10, 0x01, 0x42, 0x29, 0x5a, 0x27, 0x76,
	0x38, 0x2e, 0x72, 0x75, 0x6e, 0x2f, 0x67, 0x6f, 0x2f, 0x64, 0x73, 0x79, 0x73, 0x2f, 0x63, 0x6f,
	0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x2f, 0x72, 0x61, 0x66, 0x74, 0x2f, 0x72, 0x61, 0x66,
	0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_consensus_raft_raftproto_raftproto_proto_rawDescOnce sync.Once
	file_consensus_raft_raftproto_raftproto_proto_rawDescData = file_consensus_raft_raftproto_raftproto_proto_rawDesc
)

func file_consensus_raft_raftproto_raftproto_proto_rawDescGZIP() []byte {
	file_consensus_raft_raftproto_raftproto_proto_rawDescOnce.Do(func() {
		file_consensus_raft_raftproto_raftproto_proto_rawDescData = protoimpl.X.CompressGZIP(file_consensus_raft_raftproto_raftproto_proto_rawDescData)
	})
	return file_consensus_raft_raftproto_raftproto_proto_rawDescData
}

var file_consensus_raft_raftproto_raftproto_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_consensus_raft_raftproto_raftproto_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_consensus_raft_raftproto_raftproto_proto_goTypes = []interface{}{
	(EntryType)(0), // 0: proto.EntryType
	(*Entry)(nil),  // 1: proto.Entry
}
var file_consensus_raft_raftproto_raftproto_proto_depIdxs = []int32{
	0, // 0: proto.Entry.Type:type_name -> proto.EntryType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_consensus_raft_raftproto_raftproto_proto_init() }
func file_consensus_raft_raftproto_raftproto_proto_init() {
	if File_consensus_raft_raftproto_raftproto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_consensus_raft_raftproto_raftproto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Entry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_consensus_raft_raftproto_raftproto_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_consensus_raft_raftproto_raftproto_proto_goTypes,
		DependencyIndexes: file_consensus_raft_raftproto_raftproto_proto_depIdxs,
		EnumInfos:         file_consensus_raft_raftproto_raftproto_proto_enumTypes,
		MessageInfos:      file_consensus_raft_raftproto_raftproto_proto_msgTypes,
	}.Build()
	File_consensus_raft_raftproto_raftproto_proto = out.File
	file_consensus_raft_raftproto_raftproto_proto_rawDesc = nil
	file_consensus_raft_raftproto_raftproto_proto_goTypes = nil
	file_consensus_raft_raftproto_raftproto_proto_depIdxs = nil
}
